routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('auth.login');
//});

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('google/setauth', 'Google\GoogleController@setAuth')->name('setauth');
Route::get('google/addworksheet', 'Google\GoogleController@addWorkSheet')->name('addworksheet');

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
    Route::get('/home', 'HomeController@index')->name('relation');

    /**
     * single category routes
     */
    Route::group(['namespace' => 'Single'], function(){
        Route::resource('singlecategory', 'SingleCategoryController');
    });
    Route::post('singlecategory/change_status/{id}','Single\SingleCategoryController@change_status');
    Route::post('singlecategory/re-order', 'Single\SingleCategoryController@reOrder')->name('singlecategory.reorder');
    /**
     * collage category routes
     */
    Route::group(['namespace' => 'Collage'], function(){
        Route::resource('collagecategory', 'CollageCategoryController');
    });
    Route::get('collagehomescreen','HomeScreen\HomeScreenController@collageHomescreen')->name('collagehomescreen');
    Route::post('collagecategory/change_status/{id}','Collage\CollageCategoryController@change_status');
    Route::get('collageelements','Collage\CollageCategoryController@collageElements')->name('collageelements');
    Route::post('collageelements/re-order', 'Collage\CollageCategoryController@reOrder')->name('collageelements.reorder');
    Route::post('collagecategory/category-re-order', 'Collage\CollageCategoryController@categoryreOrder')->name('collagecategory.categoryreorder');

    Route::get('singlehomescreen','Single\SingleCategoryController@singleHomescreen')->name('singlehomescreen');


        /**
     * relation routes
     */
    Route::group(['namespace' => 'Relation'], function(){
        Route::resource('relation', 'RelationController');
    });
    Route::get('homescreen_relation','Relation\RelationController@homescreen_relation')->name('homescreen_relation');
    Route::post('relation/change_status/{id}','Relation\RelationController@change_status');

    Route::post('relation_image/re-order', 'Relation\RelationController@reOrder')->name('relation_image.reorder');
    /**
     * relation Type routes
     */
    Route::group(['namespace' => 'Relation'], function(){
        Route::resource('relationtype', 'RelationTypeController');
    });
    Route::post('relationtype/change_status/{id}','Relation\RelationTypeController@change_status');
    Route::post('relationtype/re-order', 'Relation\RelationTypeController@reOrder')->name('relationtype.reorder');
    /**
     * home Screen routes
     */
    Route::group(['namespace' => 'HomeScreen'], function(){
        Route::resource('homescreen', 'HomeScreenController');
    });

    Route::get('homescreen_type/{type}','HomeScreen\HomeScreenController@typeindex')->name('homescreen_type');
    Route::post('homescreen/change_activestatus/{id}','HomeScreen\HomeScreenController@change_activestatus');
    Route::post('homescreen/change_status/{id}','HomeScreen\HomeScreenController@change_status');
    Route::post('homescreen/is_pro', 'HomeScreen\HomeScreenController@setIsPro')->name('homescreen.set_is_pro');
    Route::post('homescreen/re-order', 'HomeScreen\HomeScreenController@reOrder')->name('homescreen.reorder');

    /**
     * Posters routes
     */
    Route::group(['namespace' => 'Posters'], function(){
        Route::resource('poster', 'PosterController');
    });

    Route::post('poster/change_status/{id}','Posters\PosterController@change_status');
    Route::post('poster/is_pro', 'Posters\PosterController@setIsPro')->name('poster.set_is_pro');
    Route::post('poster/re-order', 'Posters\PosterController@reOrder')->name('poster.reorder');
    /**
     * Stickers routes
     */
    Route::group(['namespace' => 'Sticker'], function(){
        Route::resource('sticker', 'StickerController');
    });
    Route::post('sticker/change_status/{id}','Sticker\StickerController@change_status');
    Route::post('sticker/is_pro', 'Sticker\StickerController@setIsPro')->name('sticker.set_is_pro');
    Route::post('sticker/is_color', 'Sticker\StickerController@setIsColor')->name('sticker.set_is_color');
    Route::post('sticker/re-order', 'Sticker\StickerController@reOrder')->name('sticker.reorder');
    /**
     * Category routes
     */
    Route::group(['namespace' => 'Category'], function(){
        Route::resource('category', 'CategoryController');
    });
    Route::post('category/re-order', 'Category\CategoryController@reOrder')->name('category.reorder');
    Route::post('category/change_lock/{id}','Category\CategoryController@change_lock');

    /**
     * milestone routes
     */
    Route::get('milestone','Posters\PosterController@milestone_index')->name('milestone');

    /**
     * background category routes
     */
    Route::group(['namespace' => 'Background'], function(){
        Route::resource('backgroundcategory', 'BackgorundCategoryController');
    });
    Route::post('backgroundcategory/change_status/{id}','Background\BackgorundCategoryController@change_status');
    Route::post('backgroundcategory/re-order', 'Background\BackgorundCategoryController@reOrder')->name('backgroundcategory.reorder');

    /**
     * background routes
     */

    Route::group(['namespace' => 'Background'], function(){
        Route::resource('background', 'BackgorundController');
    });

    Route::post('background/change_status/{id}','Background\BackgorundController@change_status');
    Route::post('background/is_pro', 'Background\BackgorundController@setIsPro')->name('background.set_is_pro');
    Route::post('background/re-order', 'Background\BackgorundController@reOrder')->name('background.reorder');

    /**
     * Key routes
     */
    Route::group(['namespace' => 'Setting'], function(){
        Route::resource('setting', 'SettingController');
    });
    Route::post('setting/change_status/{id}','Setting\SettingController@change_status');

    /**
     * Font routes
     */
    Route::group(['namespace' => 'Font'], function(){
        Route::resource('font', 'FontController');
    });
    Route::post('font/change_status/{id}','Font\FontController@change_status');
    Route::post('font/re-order', 'Font\FontController@reOrder')->name('font.reorder');
    Route::post('font/is_pro', 'Font\FontController@setIsPro')->name('font.set_is_pro');
});

app/Models/Relation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Relation extends Model
{
    use SoftDeletes;
    protected $table = "relations";

    public function RelationType(){
        return $this->belongsTo(RelationType::class,'relation_type_id','id');
    }
}

app/Models/RelationType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RelationType extends Model
{
   protected $table = "relation_type";

    public function Relation(){
        return $this->hasMany(Relation::class,'relation_type_id','id')->where('is_enable',1)->orderBy('order_by','asc');
    }

    public function HomeScreen(){
        return $this->hasMany(HomeScreen::class,'relation_type_id','id')->where('is_active',1)->orderBy('is_pro', 'asc')->orderBy('order_by','desc');
    }
}

app/Http/Controllers/Api/Relation/RelationApicontroller.php
<?php

namespace App\Http\Controllers\Api\Relation;

use App\Http\Controllers\Controller;
use App\Http\Resources\HomeScreenResource;
use App\Http\Resources\RelationResource;
use App\Http\Resources\RelationTypeResource;
use App\Models\HomeScreen;
use App\Models\RelationType;
use Illuminate\Http\Request;
use App\Models\Relation;
use Exception;

class RelationApicontroller extends Controller
{
    public function index(Request $request)
    {
            try {
                $relation = RelationType::with('homescreen')->where('is_active', 1)->orderBy('order_by', 'asc')->get();
                $relation = RelationTypeResource::collection($relation);
                return response()->json(['data' => $relation], 200);
            } catch
            (Exception $e) {
                return response()->json(['message' => "Relation not found..."], 422);
            }
    }

    public function getrelationfromtype(Request $request)
    {
            try {
                if ($request->relation_type_id == "") {
                    return response()->json(['message' => "Relation Type id not found..."], 422);
                }
                $relation_type = $request->relation_type_id;
                $homescreen = HomeScreen::where('relation_type_id', $relation_type)->where('is_active', 1)->orderBy('is_pro', 'asc')->orderBy('order_by', 'desc')->get();
                $homescreen = HomeScreenResource::collection($homescreen);
                return response()->json(['data' => $homescreen], 200);
            } catch
            (Exception $e) {
                return response()->json(['message' => "Relation not found..."], 422);
            }
    }

    public function getallimagesofrelation(Request $request)
    {
            try {
                if ($request->home_screen_id == "") {
                    return response()->json(['message' => "Home screen id not found..."], 422);
                }
                $home_screen_id = $request->home_screen_id;
                $relation = Relation::where('home_screen_id', $home_screen_id)->orderBy('order_by', 'asc')->get();
                $relation = relationResource::collection($relation);
                return response()->json(['data' => $relation], 200);
            } catch
            (Exception $e) {
                return response()->json(['message' => "Relation not found..."], 422);
            }
    }
}

app/Http/Controllers/Relation/RelationController.php
<?php

namespace App\Http\Controllers\Relation;

use App\Http\Controllers\Controller;
use App\Http\Requests\Relation\RelationRequest;
use App\Models\HomeScreen;
use App\Models\RelationType;
use App\Traits\ImageTrait;
use Illuminate\Http\Request;
use App\Models\Relation;
use Yajra\DataTables\DataTables;

class RelationController extends Controller
{
    /**
     * Display a relationtypelisting of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if( $request->filled('api')){
//            dd($request);
            $homescreen = HomeScreen::where('relation_type_id', $_GET['id'])->orderBy('order_by','desc')->get();
//                $relation = Relation::where('relation_type_id', $_GET['id'])->orderBy('created_at','desc')->get();
                return Datatables::of($homescreen)->make(true);
        }

//        if($request->filled('api')){
//            return Datatables::of(Relation::query())->make(true);
//        }
        $relation_id = $request->id;
        $relation= RelationType::select('id','relation_name')->where('id',$relation_id)->first();
//        $relation_name = $relation->relation_name;
        return view('pages.relation.index',compact('relation_id','relation'));
    }

    public function homescreen_relation(Request $request){
        if( $request->filled('api')) {
            $relation = Relation::where('home_screen_id', $_GET['home_screen_id'])->orderBy('order_by','asc')->get();
            return Datatables::of($relation)->make(true);
        }
        $home_screen_id = $_GET['home_screen_id'];
        $relation = Relation::select('relation_type_id')->where('home_screen_id', $_GET['home_screen_id'])->first();
        $relation_type_id = $relation->relation_type_id;
        return view('pages.homescreen.relation',compact('home_screen_id','relation_type_id'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $relation = false;
        $relationtype = RelationType::where('id', $request->relation_id )->first();
//        dd($relationtype);
//        $relationtype = RelationType::get();
        return view('pages.relation.create', compact('relation'),compact('relationtype'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RelationRequest $request)
    {
        try {
            $relation = new Relation;
            $relation->relation_type_id = $request->relation_type_id;

            if ($request->hasFile('image')) {
                $image = ImageTrait::makeImage($request->image, 'uploads/relation/');
            }
            $relation->image = $image;
            $relation->save();
            return redirect('relation'.'?id='.$relation->relation_type_id);
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Relation not added...');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Relation $relation)
    {
        $relationtype = RelationType::where('id', $relation->relation_type_id )->first();
        return view('pages.relation.create', compact('relation'),compact('relationtype'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RelationRequest $request, Relation $relation)
    {
        try {
            $relation->relation_type_id = $request->relation_type_id;

            if ($request->hasFile('image')) {
                $image = ImageTrait::makeImage($request->image, 'uploads/relation/');
            }else{
                $image = $relation->image;
            }
            $relation->image = $image;
            $relation->save();
            return redirect('relation'.'?id='.$relation->relation_type_id);
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Relation not Update...');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Relation $relation)
    {
        try {
            $relation->delete();
            return response()->json(['data' => 'Relation deleted successfully...', 'status' => '1']);
        } catch (Exception $e) {
            return response()->json(['data' => 'Relation not Deleted...', 'status' => '0']);
        }
    }

    /**
     * Active /deactive relation image
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function change_status($id)
    {
        try {
            $relation = Relation::where('id', $id)->first();
            $value = ( $_POST['data'] && $_POST['data'] == "1" ) ? 0 : 1;
            $relation->relation_type_id = $relation->relation_type_id;
            $relation->is_enable = $value;
            $relation->image = $relation->image;

            if( $relation->save()){
                return response()->json(['data' => 'Relation Status changed...', 'status' => '1']);
            }else{
                return response()->json(['data' => 'Relation Status not changed...', 'status' => '0']);
            }

        } catch (Exception $e) {
            return response()->json(['data' => 'Poster Status not changed...', 'status' => '0']);
        }
    }

    public function reOrder(Request $request)
    {
        $request->items = array_filter($request->items);
        foreach ($request->items as $key => $val) {
            $entity = Relation::find($val);
            $entity->order_by = $key;
            $entity->save();
        }
    }
}

resources/views/pages/relation/create.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container py-5" style="padding:10px;">

        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="h6 text-uppercase mb-0">Save Relation</h3>
                    </div>
                    <div class="card-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">{{ Session::get('success') }}</div>
                        @endif
                        @if(Session::has('error'))
                            <div class="alert alert-danger">{{ Session::get('error') }}</div>
                        @endif
                        <form method="post" action="{{($relation) ? route('relation.update',$relation->id) : route('relation.store')}}" enctype="multipart/form-data">
                            @csrf
                            @if($relation)
                                @method('patch')
                            @endif
                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Name</label>
                                <input type="hidden" name="relation_type_id" value="{{$relationtype->id}}">
                                <input type="text" name="relation_name" value="{{$relationtype->relation_name}}" class="form-control" readonly>
{{--                                <select name="name" class="form-control">--}}
{{--                                    <option selected disabled>--- Select Relation ---</option>--}}
{{--                                    @foreach( $relationtype as $ty )--}}
{{--                                        <option value="{{$ty->id}}" {{ ($relation) ?  ($ty->id) == $relation->relation_type_id ? "selected" : "" : (old('name')) == ($ty->id) ? "selected" : "" }}>{{$ty->relation_name}}</option>--}}
{{--                                    @endforeach--}}
{{--                                </select>--}}
                                @if ($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group prw-img">
                                <label class="form-control-label text-uppercase">Image</label>
                                <div class="col-md-3">
                                    <img src="{{($relation) ? url('storage/uploads/relation/') . '/'. $relation->image : ''}}" id="" width="50px">
                                </div>

                                <input type="file" placeholder="Relation Image" name="image" class="form-control uploadFile" value="">
                                @if ($errors->has('image'))
                                    <span class="text-danger">{{ $errors->first('image') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/relation/index.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container">
        <div class="row p-xl-5">
            <div class="col-md-9">
                <h2><a href="{{route('relationtype.index')}}"><i class="fa fa-arrow-left" aria-hidden="true">&nbsp&nbsp</i></a>{{$relation->relation_name}}</h2>
            </div>
            <div class="col-md-3">
                <a class="btn btn-lg form-control add-btn pull-right" href="{{ route('homescreen.create').'?type=2&relation_type='.$relation->id }}">Create homescreen</a>
            </div>
            <div class="col-md-12">
                <table class="table table-striped" id="relation-table">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Title</th>
                        <th>Image</th>
                        <th>Is_Active</th>
                        <th>is_home</th>
                        <th>Is_pro</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var crawlapps_baby_dashboard = {
            init: function () {
                this.datatableInit();
                this.homescreen_delete();
                this.change_status();
                this.change_profree();
                this.change_activestatus();
            },
            datatableInit: function () {
                var ajax_url = '';
                var id = this.getQueryStringValue("id");

                ajax_url = "{{ route('relation.index')}}?api=1&id="+id;
                var i = 1;
                $relation_table = $('#relation-table').DataTable({
                    "serverSide": true,
                    "destroy": true,
                    "ajax": ajax_url,
                    "columns": [
                        {"data": "id"},
                        {"data": "title"},
                        {"data": "image"},
                    ],
                    "columnDefs": [
                        {
                            "render": function (data, type, row) {
                                return i++;
                            },
                            "targets": 0,
                        },
                        {
                            "render": function (data, type, row) {
                                let url = "{{ url('storage/uploads/homescreens').'/'}}" + row.file_homescreen;
                                let r1 = "{{route('homescreen_relation',"__")}}"
                                r1 = r1.replace("__", 'home_screen_id='+row.id);
                                return (row.file_homescreen) ? `<a href="`+ r1 +`"><img height="50" width="50" src="` + url + `" ></a>` : '';
                            },
                            "targets": 2,
                        },
                        {
                            "render": function (data, type, row) {
                                var check = (row.is_active == 1) ? 'checked' : '';
                                return `<label class="label-switch switch-success">
                                    <input type="checkbox" class="switch switch-bootstrap status chng-activestatus" name="activestatus" id="activestatus" value="1"` + check + ` data-value="` + row.is_active + `" data-id="`+ row.id +`">
                                    <span class="lable"></span></label>`;

                            },
                            "targets": 3,
                        },
                        {
                            "render": function (data, type, row) {
                                var check = (row.is_home == 1) ? 'checked' : '';
                                return `<label class="label-switch switch-success">
                                    <input type="checkbox" class="switch switch-bootstrap status chng-status" name="status" id="status" value="1"` + check + ` data-value="` + row.is_home + `" data-id="`+ row.id +`">
                                    <span class="lable"></span></label>`;

                            },
                            "targets": 4,
                        },
                        {
                            "render": function (data, type, row) {
                                var disable = ( row.is_home == 1 ) ? 'disabled' : '';

                                var check = (row.is_pro == 1) ? 'checked' : '';
                                return `<label class="label-switch switch-success">
                                    <input type="checkbox" class="switch switch-bootstrap pro-free" name="status" id="is_pro" value="1"` + check + ` data-value="` + row.is_pro + `" data-id="`+ row.id +`">
                                    <span class="lable"></span></label>`;

                            },
                            "targets": 5,
                        },

                        {
                            "render": function (data, type, row) {
                                let r1 = "{{route('homescreen.edit',"__")}}"
                                let r3 = "{{route('homescreen.destroy',"__")}}";
                                r1 = r1.replace("__", row.id);
                                r3 = r3.replace("__", row.id);
                                return  `<a href="`+r1+`" class="btn btn-info"><i class="fa fa-pencil"></i></a>
                                <button class="btn btn-danger del-homescreen" data-id="`+row.id+`" type="submit"><i class="fa fa-trash-o"></i></button>`
                            },
                            "targets": 6,
                        },
                    ],
                    "pageLength": 50,
                    "lengthChange": false,
                    "orderable": false,
                    "bSort": false,
                    "bInfo": false,

                    rowReorder: true,
                    'createdRow': function (row, data, dataIndex) {
                        $(row).attr({
                            'id': data.id,
                            /*'data-webapp_code': data.webapp_id,*/
                        });
                    },
                    "fnDrawCallback": function () {
                        i=0;
                        // $('.input-checkbox').bootstrapToggle();
                    },
                });
                $relation_table.on( 'row-reorder', function ( e, details, edit ) {

                    var data = [];
                    for ( var i=0; i < details.length ; i++ ) {
                        data[details[i].newPosition] = details[i].node.id;
                    }
                    data = {
                        'items' : data,
                        "_token": "{{ csrf_token() }}",
                    };
                    $.ajax({
                        type: 'POST',
                        url:  "{{ route('homescreen.reorder')  }}",
                        data: data,
                        success: function (data) {
                            // $relation_table.ajax.reload();
                        }
                    })
                });
            },
            homescreen_delete: function () {
                $(document).on('click', '.del-homescreen', function () {
                    var id = $(this).data('id');
                    swal({
                            title: "Are you sure?",
                            text: "To delete this homescreen...",
                            icon: "warning",
                            buttons: true,
                            dangerMode: true,
                            showCancelButton: true,
                            cancelButtonText: 'Cancel',
                            closeOnConfirm: false,
                            closeOnCancel: true
                        },
                        function () {
                            let url = "{{route('homescreen.destroy',"__")}}";
                            url = url.replace("__", id);
                            $.ajax({
                                url: url,
                                type: "post",
                                data: {'_method': 'delete', '_token': "{{ csrf_token() }}"},
                                success: function (data) {
                                    swal({
                                        icon: "success",
                                    });
                                    if (data['status'] == "1") {
                                        window.location.reload();
                                    }
                                },
                            });
                        });
                });
            },
            getQueryStringValue: function (key) {
                return decodeURIComponent(window.location.search.replace(new RegExp("^(?:.*[&\\?]" + encodeURIComponent(key).replace(/[\.\+\*]/g, "\\$&") + "(?:\\=([^&]*))?)?.*$", "i"), "$1"));
            },
            change_status: function () {
                $(document).on('change', '.chng-status', function () {
                    var value = $(this).data('value');
                    var id = $(this).data('id');
                    let url = "{{url('homescreen/change_status',"__")}}";
                    url = url.replace("__", id);
                    $.ajax({
                        url: url,
                        type: "post",
                        data: {'_method': 'post', '_token': "{{ csrf_token() }}", 'data': value},
                        success: function (data) {
                            console.log(data);
                            crawlapps_baby_dashboard.datatableInit();
                            // window.location.reload();
                        },
                    });
                });
            },
            change_activestatus: function () {
                $(document).on('change', '.chng-activestatus', function () {
                    var value = $(this).data('value');
                    var id = $(this).data('id');
                    let url = "{{url('homescreen/change_activestatus',"__")}}";
                    url = url.replace("__", id);
                    $.ajax({
                        url: url,
                        type: "post",
                        data: {'_method': 'post', '_token': "{{ csrf_token() }}", 'data': value},
                        success: function (data) {
                            console.log(data);
                            // window.location.reload();
                        },
                    });
                });
            },
            change_profree: function () {
                $(document).on('change', '.pro-free', function () {
                    let data = {
                        is_pro: $(this).data('value'),
                        id: $(this).data('id'),
                        "_token": "{{ csrf_token() }}",
                    };

                    $.ajax({
                        url: "{{route('homescreen.set_is_pro')}}",
                        type: "post",
                        data: data,
                        success: function (data) {
                            console.log(data);
                            // window.location.reload();
                        },
                    });
                });
            },
        };

        $(document).ready(function () {
            crawlapps_baby_dashboard.init();
        });
    </script>
@endsection