routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('auth.login');
//});

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('google/setauth', 'Google\GoogleController@setAuth')->name('setauth');
Route::get('google/addworksheet', 'Google\GoogleController@addWorkSheet')->name('addworksheet');

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
    Route::get('/home', 'HomeController@index')->name('relation');

    /**
     * single category routes
     */
    Route::group(['namespace' => 'Single'], function(){
        Route::resource('singlecategory', 'SingleCategoryController');
    });
    Route::post('singlecategory/change_status/{id}','Single\SingleCategoryController@change_status');
    Route::post('singlecategory/re-order', 'Single\SingleCategoryController@reOrder')->name('singlecategory.reorder');
    /**
     * collage category routes
     */
    Route::group(['namespace' => 'Collage'], function(){
        Route::resource('collagecategory', 'CollageCategoryController');
    });
    Route::get('collagehomescreen','HomeScreen\HomeScreenController@collageHomescreen')->name('collagehomescreen');
    Route::post('collagecategory/change_status/{id}','Collage\CollageCategoryController@change_status');
    Route::get('collageelements','Collage\CollageCategoryController@collageElements')->name('collageelements');
    Route::post('collageelements/re-order', 'Collage\CollageCategoryController@reOrder')->name('collageelements.reorder');
    Route::post('collagecategory/category-re-order', 'Collage\CollageCategoryController@categoryreOrder')->name('collagecategory.categoryreorder');

    Route::get('singlehomescreen','Single\SingleCategoryController@singleHomescreen')->name('singlehomescreen');


        /**
     * relation routes
     */
    Route::group(['namespace' => 'Relation'], function(){
        Route::resource('relation', 'RelationController');
    });
    Route::get('homescreen_relation','Relation\RelationController@homescreen_relation')->name('homescreen_relation');
    Route::post('relation/change_status/{id}','Relation\RelationController@change_status');

    Route::post('relation_image/re-order', 'Relation\RelationController@reOrder')->name('relation_image.reorder');
    /**
     * relation Type routes
     */
    Route::group(['namespace' => 'Relation'], function(){
        Route::resource('relationtype', 'RelationTypeController');
    });
    Route::post('relationtype/change_status/{id}','Relation\RelationTypeController@change_status');
    Route::post('relationtype/re-order', 'Relation\RelationTypeController@reOrder')->name('relationtype.reorder');
    /**
     * home Screen routes
     */
    Route::group(['namespace' => 'HomeScreen'], function(){
        Route::resource('homescreen', 'HomeScreenController');
    });

    Route::get('homescreen_type/{type}','HomeScreen\HomeScreenController@typeindex')->name('homescreen_type');
    Route::post('homescreen/change_activestatus/{id}','HomeScreen\HomeScreenController@change_activestatus');
    Route::post('homescreen/change_status/{id}','HomeScreen\HomeScreenController@change_status');
    Route::post('homescreen/is_pro', 'HomeScreen\HomeScreenController@setIsPro')->name('homescreen.set_is_pro');
    Route::post('homescreen/re-order', 'HomeScreen\HomeScreenController@reOrder')->name('homescreen.reorder');

    /**
     * Posters routes
     */
    Route::group(['namespace' => 'Posters'], function(){
        Route::resource('poster', 'PosterController');
    });

    Route::post('poster/change_status/{id}','Posters\PosterController@change_status');
    Route::post('poster/is_pro', 'Posters\PosterController@setIsPro')->name('poster.set_is_pro');
    Route::post('poster/re-order', 'Posters\PosterController@reOrder')->name('poster.reorder');
    /**
     * Stickers routes
     */
    Route::group(['namespace' => 'Sticker'], function(){
        Route::resource('sticker', 'StickerController');
    });
    Route::post('sticker/change_status/{id}','Sticker\StickerController@change_status');
    Route::post('sticker/is_pro', 'Sticker\StickerController@setIsPro')->name('sticker.set_is_pro');
    Route::post('sticker/is_color', 'Sticker\StickerController@setIsColor')->name('sticker.set_is_color');
    Route::post('sticker/re-order', 'Sticker\StickerController@reOrder')->name('sticker.reorder');
    /**
     * Category routes
     */
    Route::group(['namespace' => 'Category'], function(){
        Route::resource('category', 'CategoryController');
    });
    Route::post('category/re-order', 'Category\CategoryController@reOrder')->name('category.reorder');
    Route::post('category/change_lock/{id}','Category\CategoryController@change_lock');

    /**
     * milestone routes
     */
    Route::get('milestone','Posters\PosterController@milestone_index')->name('milestone');

    /**
     * background category routes
     */
    Route::group(['namespace' => 'Background'], function(){
        Route::resource('backgroundcategory', 'BackgorundCategoryController');
    });
    Route::post('backgroundcategory/change_status/{id}','Background\BackgorundCategoryController@change_status');
    Route::post('backgroundcategory/re-order', 'Background\BackgorundCategoryController@reOrder')->name('backgroundcategory.reorder');

    /**
     * background routes
     */

    Route::group(['namespace' => 'Background'], function(){
        Route::resource('background', 'BackgorundController');
    });

    Route::post('background/change_status/{id}','Background\BackgorundController@change_status');
    Route::post('background/is_pro', 'Background\BackgorundController@setIsPro')->name('background.set_is_pro');
    Route::post('background/re-order', 'Background\BackgorundController@reOrder')->name('background.reorder');

    /**
     * Key routes
     */
    Route::group(['namespace' => 'Setting'], function(){
        Route::resource('setting', 'SettingController');
    });
    Route::post('setting/change_status/{id}','Setting\SettingController@change_status');

    /**
     * Font routes
     */
    Route::group(['namespace' => 'Font'], function(){
        Route::resource('font', 'FontController');
    });
    Route::post('font/change_status/{id}','Font\FontController@change_status');
    Route::post('font/re-order', 'Font\FontController@reOrder')->name('font.reorder');
    Route::post('font/is_pro', 'Font\FontController@setIsPro')->name('font.set_is_pro');
});

app/Models/Background.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Background extends Model
{
    use SoftDeletes;
    protected $table = "backgrounds";



}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = "categories";

    public function sticker(){
        return $this->hasMany(Sticker::class,'category_id','id')->where('is_enable',1)->orderBy('is_pro', 'asc')->orderBy('order_by','asc');
    }
}

app/Http/Controllers/Api/Background/BackgroundApiController.php
<?php

namespace App\Http\Controllers\Api\Background;

use App\Http\Controllers\Controller;
use App\Http\Resources\BackgroundCategoryResource;
use App\Models\BackgroundCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redis;

class BackgroundApiController extends Controller
{
    public function index()
    {
        try {
            // cache key = env('CACHE_PREFIX') . categories
            $cacheKey = 'background';
            $entity = BackgroundCategory::with('background')->where('is_active', 1)->orderBy('order_by', 'asc')->get();
            $entity = BackgroundCategoryResource::collection($entity);

            return response()->json(['data' =>$entity] , 200);
//            Redis::del($cacheKey);
//            Redis::set($cacheKey, json_encode($entity));
//
//            if (\Request::is('api*')) {
//                return response()->json([
//                    "status" => true,
//                    "message" => "Category list get successfully.",
//                    'data' => (!empty(Redis::get($cacheKey))) ? json_decode(Redis::get($cacheKey)) : $entity
//                ], 200);
//            }
//            return json_encode($entity);
        } catch
        (Exception $e) {
            return response()->json(['message' => "Background not found..."], 422);
        }
    }
}

app/Http/Controllers/Api/Category/CategoryApicontroller.php
<?php

namespace App\Http\Controllers\Api\Category;

use App\Http\Controllers\Controller;
use App\Http\Resources\CategoryResource;
use App\Models\Category;
use App\Models\Sticker;
use Illuminate\Http\Request;

class CategoryApicontroller extends Controller
{
    public function index(Request $request)
    {
        try {
            $sticker = Category::with('sticker')->where('is_lock', '1')->orderBy('order_by', 'asc')->get();
            $sticker = CategoryResource::collection($sticker);
            return response()->json(['data' => $sticker], 200);
        } catch
        (Exception $e) {
            return response()->json(['message' => "Sticker not found..."], 422);
        }
    }
}

app/Http/Controllers/Background/BackgorundCategoryController.php
<?php

namespace App\Http\Controllers\Background;

use App\Http\Controllers\Api\Background\BackgroundApiController;
use App\Http\Controllers\Controller;
use App\Http\Requests\Background\BackgroundCategoryRequest;
use App\Models\BackgroundCategory;
use App\Traits\ImageTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redis;
use Yajra\DataTables\DataTables;

class BackgorundCategoryController extends Controller
{
    use ImageTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->filled('api')){
            return Datatables::of(BackgroundCategory::orderBy('order_by','asc')->get())->make(true);
        }
        return view('pages.background.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $backgroundcategory = false;
        return view('pages.background.category.create', compact('backgroundcategory'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BackgroundCategoryRequest $request)
    {
        try {
            $category = new BackgroundCategory;
            $image = ImageTrait::makeImage($request->file_category, 'uploads/backgroundcategory/');

//            // for compress file
//            $this->destinationPath = public_path('/storage/uploads/backgroundcategory/');
//            $this->thumbnailDestinationPath = public_path('/storage/uploads/backgroundcategory/thumbnails/');
//            if (!file_exists( $this->thumbnailDestinationPath )) {
//                mkdir($this->thumbnailDestinationPath, 0777, true);
//            }
//            $this->compress_image($this->destinationPath . $image, $this->thumbnailDestinationPath . $image, env('QUALITY'));

            $category->name = convert_char_UTF_8($request->name);
            $category->file_background_category = $image;
            $category->order_by = BackgroundCategory::count() + 1;
            $category->save();

//            $this->setCache();
            return redirect('backgroundcategory');
//            return redirect()->back()->with('success', 'Category Added successfully...');


        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Category not added...');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(BackgroundCategory $backgroundcategory)
    {
        return view('pages.background.category.create', compact('backgroundcategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BackgroundCategoryRequest $request, BackgroundCategory $backgroundcategory)
    {
        try {

            if( $request->file_category ){
                $image = ImageTrait::makeImage($request->file_category, 'uploads/backgroundcategory/');
            }else{
                $image = $backgroundcategory->file_background_category;
            }

            $backgroundcategory->name = convert_char_UTF_8($request->name);
            $backgroundcategory->file_background_category = $image;
            $backgroundcategory->save();

//            $this->setCache();
            return redirect('backgroundcategory');
//            return redirect()->back()->with('success', 'Category Added successfully...');


        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Category not added...');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(BackgroundCategory $backgroundcategory)
    {
        try {
            $path = \Storage::path('uploads/backgroundcategory/'.$backgroundcategory->file_background_category);
            if(file_exists($path)){
                unlink($path);
            }
            $backgroundcategory->delete();

//            $this->setCache();
            return response()->json(['data' => 'Category deleted successfully...', 'status' => '1']);
        } catch (Exception $e) {
            return response()->json(['data' => 'Category not Deleted...', 'status' => '0']);
        }
    }

    public function change_status($id)
    {
        try {
            $value = ( $_POST['data'] && $_POST['data'] == "1" ) ? 0 : 1;
            $entity = BackgroundCategory::where('id', $id)->first();
            $entity->is_active = $value;

            \DB::table('backgrounds')
                ->where('background_category_id', $id)
                ->update(['is_active' => $value]);

//            $this->setCache();
            if( $entity->save()){
                return response()->json(['data' => 'category Status changed...', 'status' => '1']);
            }else{
                return response()->json(['data' => 'category Status not changed...', 'status' => '0']);
            }

        } catch (Exception $e) {
            return response()->json(['data' => 'category Status not changed...', 'status' => '0']);
        }
    }

    public function reOrder(Request $request)
    {
        $request->items = array_filter($request->items);
        foreach ($request->items as $key => $val) {
            $entity = BackgroundCategory::find($val);
            $entity->order_by = $key;
            $entity->save();
        }
//        $this->setCache();
    }

    public function setCache(){
        $back = new BackgorundController();
        $back->setCache();
    }
}

resources/views/pages/background/category/create.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container py-5" style="padding:10px;">

        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="h6 text-uppercase mb-0">Save Category</h3>
                    </div>
                    <div class="card-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">{{ Session::get('success') }}</div>
                        @endif
                        @if(Session::has('error'))
                            <div class="alert alert-danger">{{ Session::get('error') }}</div>
                        @endif
                        <form method="post" action="{{($backgroundcategory) ? route('backgroundcategory.update',$backgroundcategory->id) : route('backgroundcategory.store')}}" enctype="multipart/form-data">
                            @csrf
                            @if($backgroundcategory)
                                @method('patch')
                            @endif
                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Name</label>
                                <input type="text" placeholder="Category name" name="name" class="form-control" value="{{($backgroundcategory) ? $backgroundcategory->name : old('name')}}">
                                @if ($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group homescreen prw-img">
                                <label class="form-control-label text-uppercase">Image</label>
                                <div class="col-md-3">
                                    <img
                                        src="{{($backgroundcategory) ? url('storage/uploads/backgroundcategory/') . '/'. $backgroundcategory->file_background_category : ''}}"
                                        id="" width="50px">
                                </div>

                                <input type="file" placeholder="" name="file_category" id="file_category" class="form-control uploadFile" value="{{($backgroundcategory) ? $backgroundcategory->file_background_category : old('file_category')}}">
                                @if ($errors->has('file_category'))
                                    <span class="text-danger">{{ $errors->first('file_category') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/background/category/index.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container">
        <div class="row p-xl-5">
            <div class="col-md-9">
                <h2>Background Category</h2>
            </div>
            <div class="col-md-3">
                <a class="btn btn-lg form-control add-btn pull-right" href="{{ route('backgroundcategory.create') }}">Create Background Category</a>
            </div>
            <div class="col-md-12">
                <table class="table table-striped" id="backgroundcategory-table">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Image</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var crawlapps_baby_dashboard = {
            init: function () {
                this.datatableInit();
                this.backgroundcategory_delete();
                this.change_status();
            },
            datatableInit: function(){
                var ajax_url = '';
                ajax_url = "{{ route('backgroundcategory.index')}}?api=1";
                var i=1;

                $backgroundcategory_table = $('#backgroundcategory-table').DataTable({
                    "serverSide": true,
                    "destroy": true,
                    "ajax": ajax_url,
                    "columns": [
                        {"data": "id"},
                        {"data": "name"},
                    ],
                    "columnDefs": [
                        {
                            "render": function (data, type, row) {
                                return i++;
                            },
                            "targets": 0,
                        },
                        {
                            "render": function (data, type, row) {
                                let r1 = "{{route('background.index',"__")}}"
                                r1 = r1.replace("__", "category_id="+row.id);
                                return `<a href="`+r1+`" >`+ row.name + `</a>`;
                            },
                            "targets": 1,
                        },
                        {
                            "render": function (data, type, row) {
                                let url = "{{ url('storage/uploads/backgroundcategory').'/'}}"+row.file_background_category;
                                return  (row.file_background_category) ? `<img height="50" width="50" src="`+url+`" >` : '';
                            },
                            "targets": 2,
                        },
                        {
                            "render": function (data, type, row) {
                                var check = (row.is_active == 1) ? 'checked' : '';
                                return `<label class="label-switch switch-success">
                                    <input type="checkbox" class="switch switch-bootstrap status chng-status" name="status" id="status" value="1"` + check + ` data-value="` + row.is_active + `" data-id="`+ row.id +`">
                                    <span class="lable"></span></label>`;

                            },
                            "targets": 3,
                        },
                        {
                            "render": function (data, type, row) {
                                let r1 = "{{route('backgroundcategory.edit',"__")}}"
                                let r3 = "{{route('backgroundcategory.destroy',"__")}}";
                                r1 = r1.replace("__", row.id);
                                r3 = r3.replace("__", row.id);
                                return  `<a href="`+r1+`" class="btn btn-info"><i class="fa fa-pencil"></i></a>
                                    <button class="btn btn-danger del-category" data-id="`+row.id+`"  type="submit"><i class="fa fa-trash-o"></i></button>`
                            },
                            "targets": 4,
                        },
                    ],
                    "pageLength": 50,
                    "lengthChange": false,
                    "orderable": false,
                    "bSort": false,
                    "bInfo": false,

                    rowReorder: true,
                    'createdRow': function (row, data, dataIndex) {
                        $(row).attr({
                            'id': data.id,
                            /*'data-webapp_code': data.webapp_id,*/
                        });
                    },
                    "fnDrawCallback": function() {
                        i=0;
                        // $('.input-checkbox').bootstrapToggle();
                    },
                });
                $backgroundcategory_table.on( 'row-reorder', function ( e, details, edit ) {

                    var data = [];
                    for ( var i=0; i < details.length ; i++ ) {
                        data[details[i].newPosition] = details[i].node.id;
                    }
                    data = {
                        'items' : data,
                        "_token": "{{ csrf_token() }}",
                    };
                    $.ajax({
                        type: 'POST',
                        url:  "{{ route('backgroundcategory.reorder')  }}",
                        data: data,
                        success: function (data) {
                            $backgroundcategory_table.ajax.reload();
                        }
                    })
                });
            },
            backgroundcategory_delete: function () {
                $(document).on('click', '.del-category', function () {
                    var id = $(this).data('id');
                    swal({
                            title: "Are you sure?",
                            text: "To delete this Category...",
                            icon: "warning",
                            buttons: true,
                            dangerMode: true,
                            showCancelButton: true,
                            cancelButtonText: 'Cancel',
                            closeOnConfirm: false,
                            closeOnCancel: true
                        },
                        function () {
                            let url = "{{route('backgroundcategory.destroy',"__")}}";
                            url = url.replace("__", id);
                            $.ajax({
                                url: url,
                                type: "post",
                                data: {'_method': 'delete', '_token': "{{ csrf_token() }}"},
                                success: function (data) {
                                    swal({
                                        icon: "success",
                                    });
                                    if (data['status'] == "1") {
                                        window.location.reload();
                                    }
                                },
                            });
                        });
                });
            },

            change_status: function () {
                $(document).on('change', '.chng-status', function () {
                    var value = $(this).data('value');
                    var id = $(this).data('id');
                    let url = "{{url('backgroundcategory/change_status',"__")}}";
                    url = url.replace("__", id);
                    $.ajax({
                        url: url,
                        type: "post",
                        data: {'_method': 'post', '_token': "{{ csrf_token() }}", 'data': value},
                        success: function (data) {
                            console.log(data);
                            // window.location.reload();
                        },
                    });
                });
            },
        };

        $(document).ready(function(){
            crawlapps_baby_dashboard.init();
        });
    </script>
@endsection