routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('auth.login');
//});

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('google/setauth', 'Google\GoogleController@setAuth')->name('setauth');
Route::get('google/addworksheet', 'Google\GoogleController@addWorkSheet')->name('addworksheet');

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
    Route::get('/home', 'HomeController@index')->name('relation');

    /**
     * single category routes
     */
    Route::group(['namespace' => 'Single'], function(){
        Route::resource('singlecategory', 'SingleCategoryController');
    });
    Route::post('singlecategory/change_status/{id}','Single\SingleCategoryController@change_status');
    Route::post('singlecategory/re-order', 'Single\SingleCategoryController@reOrder')->name('singlecategory.reorder');
    /**
     * collage category routes
     */
    Route::group(['namespace' => 'Collage'], function(){
        Route::resource('collagecategory', 'CollageCategoryController');
    });
    Route::get('collagehomescreen','HomeScreen\HomeScreenController@collageHomescreen')->name('collagehomescreen');
    Route::post('collagecategory/change_status/{id}','Collage\CollageCategoryController@change_status');
    Route::get('collageelements','Collage\CollageCategoryController@collageElements')->name('collageelements');
    Route::post('collageelements/re-order', 'Collage\CollageCategoryController@reOrder')->name('collageelements.reorder');
    Route::post('collagecategory/category-re-order', 'Collage\CollageCategoryController@categoryreOrder')->name('collagecategory.categoryreorder');

    Route::get('singlehomescreen','Single\SingleCategoryController@singleHomescreen')->name('singlehomescreen');


        /**
     * relation routes
     */
    Route::group(['namespace' => 'Relation'], function(){
        Route::resource('relation', 'RelationController');
    });
    Route::get('homescreen_relation','Relation\RelationController@homescreen_relation')->name('homescreen_relation');
    Route::post('relation/change_status/{id}','Relation\RelationController@change_status');

    Route::post('relation_image/re-order', 'Relation\RelationController@reOrder')->name('relation_image.reorder');
    /**
     * relation Type routes
     */
    Route::group(['namespace' => 'Relation'], function(){
        Route::resource('relationtype', 'RelationTypeController');
    });
    Route::post('relationtype/change_status/{id}','Relation\RelationTypeController@change_status');
    Route::post('relationtype/re-order', 'Relation\RelationTypeController@reOrder')->name('relationtype.reorder');
    /**
     * home Screen routes
     */
    Route::group(['namespace' => 'HomeScreen'], function(){
        Route::resource('homescreen', 'HomeScreenController');
    });

    Route::get('homescreen_type/{type}','HomeScreen\HomeScreenController@typeindex')->name('homescreen_type');
    Route::post('homescreen/change_activestatus/{id}','HomeScreen\HomeScreenController@change_activestatus');
    Route::post('homescreen/change_status/{id}','HomeScreen\HomeScreenController@change_status');
    Route::post('homescreen/is_pro', 'HomeScreen\HomeScreenController@setIsPro')->name('homescreen.set_is_pro');
    Route::post('homescreen/re-order', 'HomeScreen\HomeScreenController@reOrder')->name('homescreen.reorder');

    /**
     * Posters routes
     */
    Route::group(['namespace' => 'Posters'], function(){
        Route::resource('poster', 'PosterController');
    });

    Route::post('poster/change_status/{id}','Posters\PosterController@change_status');
    Route::post('poster/is_pro', 'Posters\PosterController@setIsPro')->name('poster.set_is_pro');
    Route::post('poster/re-order', 'Posters\PosterController@reOrder')->name('poster.reorder');
    /**
     * Stickers routes
     */
    Route::group(['namespace' => 'Sticker'], function(){
        Route::resource('sticker', 'StickerController');
    });
    Route::post('sticker/change_status/{id}','Sticker\StickerController@change_status');
    Route::post('sticker/is_pro', 'Sticker\StickerController@setIsPro')->name('sticker.set_is_pro');
    Route::post('sticker/is_color', 'Sticker\StickerController@setIsColor')->name('sticker.set_is_color');
    Route::post('sticker/re-order', 'Sticker\StickerController@reOrder')->name('sticker.reorder');
    /**
     * Category routes
     */
    Route::group(['namespace' => 'Category'], function(){
        Route::resource('category', 'CategoryController');
    });
    Route::post('category/re-order', 'Category\CategoryController@reOrder')->name('category.reorder');
    Route::post('category/change_lock/{id}','Category\CategoryController@change_lock');

    /**
     * milestone routes
     */
    Route::get('milestone','Posters\PosterController@milestone_index')->name('milestone');

    /**
     * background category routes
     */
    Route::group(['namespace' => 'Background'], function(){
        Route::resource('backgroundcategory', 'BackgorundCategoryController');
    });
    Route::post('backgroundcategory/change_status/{id}','Background\BackgorundCategoryController@change_status');
    Route::post('backgroundcategory/re-order', 'Background\BackgorundCategoryController@reOrder')->name('backgroundcategory.reorder');

    /**
     * background routes
     */

    Route::group(['namespace' => 'Background'], function(){
        Route::resource('background', 'BackgorundController');
    });

    Route::post('background/change_status/{id}','Background\BackgorundController@change_status');
    Route::post('background/is_pro', 'Background\BackgorundController@setIsPro')->name('background.set_is_pro');
    Route::post('background/re-order', 'Background\BackgorundController@reOrder')->name('background.reorder');

    /**
     * Key routes
     */
    Route::group(['namespace' => 'Setting'], function(){
        Route::resource('setting', 'SettingController');
    });
    Route::post('setting/change_status/{id}','Setting\SettingController@change_status');

    /**
     * Font routes
     */
    Route::group(['namespace' => 'Font'], function(){
        Route::resource('font', 'FontController');
    });
    Route::post('font/change_status/{id}','Font\FontController@change_status');
    Route::post('font/re-order', 'Font\FontController@reOrder')->name('font.reorder');
    Route::post('font/is_pro', 'Font\FontController@setIsPro')->name('font.set_is_pro');
});

app/Http/Controllers/Api/Collage/CollageApicontroller.php
<?php

namespace App\Http\Controllers\Api\Collage;

use App\Http\Controllers\Controller;
use App\Http\Resources\CollageResource;
use App\Http\Resources\HomeScreenResource;
use App\Models\HomeScreen;
use App\Models\Monthly_Collage;
use Illuminate\Http\Request;

class collageApicontroller extends Controller
{
//   public function index(Request $request){
//       try {
//           if( $request->home_screen_id == "" ){
//               return response()->json(['data' => "Enter HomeScreen id..."],422);
//           }
//           $collage = Monthly_Collage::select('id','position','image')->where('home_screen_id', $request->home_screen_id)->get();
//           $collage = CollageResource::collection($collage);
//           return response()->json(['data' => $collage],200);
//       } catch
//       (Exception $e) {
//           return response()->json(['data' => "Collages not found..."] , 422);
//       }
//   }

    public function index(Request $request)
    {
            try {
                $collage = HomeScreen::with('collage')->where('is_active', 1)->where('type', 3)->orderBy('is_pro', 'asc')->orderBy('order_by', 'desc')->get();
                $collage = HomeScreenResource::collection($collage);
                return response()->json(['data' => $collage], 200);
            } catch
            (Exception $e) {
                return response()->json(['message' => "Collages not found..."], 422);
            }
    }
}

app/Http/Controllers/Api/Collage/CollageCategoryController.php
<?php

namespace App\Http\Controllers\Api\Collage;

use App\Http\Controllers\Controller;
use App\Http\Resources\CollageCategoryResource;
use App\Http\Resources\HomeScreenResource;
use App\Models\CollageCategory;
use App\Models\HomeScreen;
use Illuminate\Http\Request;

class CollageCategoryController extends Controller
{
    public function getCollageCategory(Request $request)
    {
            try {
                $category = CollageCategory::orderBy('order_by', 'desc')->where('is_active', 1)->get();

                return response()->json(['data' => CollageCategoryResource::collection($category)], 200);
            } catch
            (Exception $e) {
                return response()->json(['message' => "Collage category not found..."], 422);
            }
    }

    public function getCollageHomescreen()
    {
            try {
                $entity = HomeScreen::where('type', 3)->where('is_active', 1)->orderBy('order_by', 'desc')->get();

                return response()->json(['data' => HomeScreenResource::collection($entity)], 200);
            } catch
            (Exception $e) {
                return response()->json(['message' => "Homescreen not found..."], 422);
            }
    }
}

app/Http/Controllers/Collage/CollageCategoryController.php
<?php

namespace App\Http\Controllers\Collage;

use App\Http\Controllers\Controller;
use App\Http\Requests\Collage\CollageCategoryRequest;
use App\Models\CollageCategory;
use App\Models\HomeScreen;
use App\Models\Monthly_Collage;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class CollageCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->filled('api')){
            return Datatables::of(CollageCategory::orderBy('order_by','desc')->get())->make(true);
        }
        return view('pages.collage.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $collagecategory = false;
        return view('pages.collage.create', compact('collagecategory'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CollageCategoryRequest $request)
    {
        try {
            $category = new CollageCategory;
            $category->name = convert_char_UTF_8($request->name);
            $category->order_by = CollageCategory::count() + 1;
            $category->save();
            return redirect("collagecategory");
//            return redirect()->back()->with('success', 'RelationType Added successfully...');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'category not added...');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(CollageCategory $collagecategory)
    {
        return view('pages.collage.create', compact('collagecategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CollageCategoryRequest $request, CollageCategory $collagecategory)
    {
        try {
            $collagecategory->name = convert_char_UTF_8($request->name);

            $collagecategory->save();
            return redirect("collagecategory");
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'category not added...');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(CollageCategory $collagecategory)
    {
        try {
            $collagecategory->delete();
            return response()->json(['data' => 'Category deleted successfully...', 'status' => '1']);
        } catch (Exception $e) {
            return response()->json(['data' => 'Category not Deleted...', 'status' => '0']);
        }
    }
    // redirect single category to collage index balde

    public function collageHomescreen(Request $request){
        $category_id = $request->id;
        if ($request->filled('api')) {
            $entity = HomeScreen::with('collage')->where('type', '3')->where('collage_category_id', $category_id)->orderBy('order_by', 'asc')->get();
            return Datatables::of($entity)->make(true);
        }

        $category= CollageCategory::select('id','name')->where('id',$category_id)->first();

        return view('pages.homescreen.collages',compact('category_id','category'));
    }

    public function change_status($id)
    {
        try {
            $value = ( $_POST['data'] && $_POST['data'] == "1" ) ? 0 : 1;
            $entity = CollageCategory::where('id', $id)->first();
            $entity->is_active = $value;

            \DB::table('home_screens')
                ->where('collage_category_id', $id)
                ->update(['is_active' => $value]);

            if( $entity->save()){
                return response()->json(['data' => 'category Status changed...', 'status' => '1']);
            }else{
                return response()->json(['data' => 'category Status not changed...', 'status' => '0']);
            }

        } catch (Exception $e) {
            return response()->json(['data' => 'category Status not changed...', 'status' => '0']);
        }
    }

    public function collageElements(Request $request){
        $homescreen_id = $request->id;
        if ($request->filled('api')) {
            $entity = Monthly_Collage::where('home_screen_id', $homescreen_id)->orderBy('position', 'asc')->get();
            return Datatables::of($entity)->make(true);
        }
        $homescreen = HomeScreen::select('collage_category_id')->where('id', $homescreen_id)->first();
        $collage_category = $homescreen->collage_category_id;

        return view('pages.homescreen.collage-element',compact('collage_category'));
    }
    public function reOrder(Request $request)
    {
        $request->items = array_filter($request->items);
        foreach ($request->items as $key => $val) {
            $entity = Monthly_Collage::find($val);
            $entity->position = $key;
            $entity->save();
        }
    }

    public function categoryreOrder(Request $request)
    {
        $request->items = array_filter($request->items);
        foreach ($request->items as $key => $val) {
            $entity = CollageCategory::find($val);
            $entity->order_by = $key;
            $entity->save();
        }
    }
}

resources/views/pages/collage/create.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container py-5" style="padding:10px;">

        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="h6 text-uppercase mb-0">Save Category</h3>
                    </div>
                    <div class="card-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">{{ Session::get('success') }}</div>
                        @endif
                        @if(Session::has('error'))
                            <div class="alert alert-danger">{{ Session::get('error') }}</div>
                        @endif
                        <form method="post" action="{{($collagecategory) ? route('collagecategory.update',$collagecategory->id) : route('collagecategory.store')}}" enctype="multipart/form-data">
                            @csrf
                            @if($collagecategory)
                                @method('patch')
                            @endif
                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Name</label>
                                <input type="text" placeholder="Catgeory Name" name="name" class="form-control" value="{{(@$collagecategory) ? $collagecategory->name :  old('name') }}">
                                @if ($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/collage/index.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container">
        <div class="row p-xl-5">
            <div class="col-md-9">
                <h2>Collage Type</h2>
            </div>
            <div class="col-md-3">
                <a class="btn btn-lg form-control add-btn pull-right" href="{{ route('collagecategory.create') }}">Create Category</a>
            </div>
            <div class="col-md-12">
                <table class="table table-striped" id="collage-table">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Is_Active</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var crawlapps_baby_dashboard = {
            init: function () {
                this.datatableInit();
                this.collagecategory_delete();
                this.change_status();
            },
            datatableInit: function(){
                var ajax_url = '';
                ajax_url = "{{ route('collagecategory.index')}}?api=1";
                var i=1;
                $collage_table = $('#collage-table').DataTable({
                    "serverSide": true,
                    "destroy": true,
                    "ajax": ajax_url,
                    "columns": [
                        {"data": "id"},
                    ],
                    "columnDefs": [
                        {
                            "render": function (data, type, row) {
                                return i++;
                            },
                            "targets": 0,
                        },
                        {
                            "render": function (data, type, row) {
                                let r1 = "{{url('collagehomescreen?id=')}}" + row.id;
                                return `<a href="` + r1 + `">`+ row.name + `</a>`;
                            },
                            "targets": 1,
                        },
                        {
                            "render": function (data, type, row) {
                                var check = (row.is_active == 1) ? 'checked' : '';
                                return `<label class="label-switch switch-success">
                                    <input type="checkbox" class="switch switch-bootstrap status chng-status" name="status" id="status" value="1"` + check + ` data-value="` + row.is_active + `" data-id="`+ row.id +`">
                                    <span class="lable"></span></label>`;

                            },
                            "targets": 2,
                        },
                        {
                            "render": function (data, type, row) {
                                let r1 = "{{route('collagecategory.edit',"__")}}"
                                r1 = r1.replace("__", row.id);
                                return  `<a href="`+r1+`" class="btn btn-info"><i class="fa fa-pencil"></i></a>
                                    <button class="btn btn-danger del-collagecategory" data-id="`+row.id+`"  type="submit"><i class="fa fa-trash-o"></i></button>`
                            },
                            "targets": 3,
                        },
                    ],
                    "pageLength": 50,
                    "lengthChange": false,
                    "orderable": false,
                    "bSort": false,
                    "bInfo": false,

                    rowReorder: true,
                    'createdRow': function (row, data, dataIndex) {
                        $(row).attr({
                            'id': data.id,
                            /*'data-webapp_code': data.webapp_id,*/
                        });
                    },
                    "fnDrawCallback": function() {
                        i=0;
                        // $('.input-checkbox').bootstrapToggle();
                    },
                });
                $collage_table.on( 'row-reorder', function ( e, details, edit ) {

                    var data = [];
                    for ( var i=0; i < details.length ; i++ ) {
                        data[details[i].newPosition] = details[i].node.id;
                    }
                    data = {
                        'items' : data,
                        "_token": "{{ csrf_token() }}",
                    };
                    $.ajax({
                        type: 'POST',
                        url:  "{{ route('collagecategory.categoryreorder')  }}",
                        data: data,
                        success: function (data) {
                            // $collage_table.ajax.reload();
                        }
                    })
                });
            },
            collagecategory_delete: function () {
                $(document).on('click', '.del-collagecategory', function () {
                    var id = $(this).data('id');
                    swal({
                            title: "Are you sure?",
                            text: "To delete this category...",
                            icon: "warning",
                            buttons: true,
                            dangerMode: true,
                            showCancelButton: true,
                            cancelButtonText: 'Cancel',
                            closeOnConfirm: false,
                            closeOnCancel: true
                        },
                        function () {
                            let url = "{{route('collagecategory.destroy',"__")}}";
                            url = url.replace("__", id);
                            $.ajax({
                                url: url,
                                type: "post",
                                data: {'_method': 'delete', '_token': "{{ csrf_token() }}"},
                                success: function (data) {
                                    swal({
                                        icon: "success",
                                    });
                                    if (data['status'] == "1") {
                                        window.location.reload();
                                    }
                                },
                            });
                        });
                });
            },
            change_status: function () {
                $(document).on('change', '.chng-status', function () {
                    var value = $(this).data('value');
                    var id = $(this).data('id');
                    let url = "{{url('collagecategory/change_status',"__")}}";
                    url = url.replace("__", id);
                    $.ajax({
                        url: url,
                        type: "post",
                        data: {'_method': 'post', '_token': "{{ csrf_token() }}", 'data': value},
                        success: function (data) {
                            console.log(data);
                            // window.location.reload();
                        },
                    });
                });
            },
        };

        $(document).ready(function(){
            crawlapps_baby_dashboard.init();
        });
    </script>
@endsection