routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('auth.login');
//});

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('google/setauth', 'Google\GoogleController@setAuth')->name('setauth');
Route::get('google/addworksheet', 'Google\GoogleController@addWorkSheet')->name('addworksheet');

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
    Route::get('/home', 'HomeController@index')->name('relation');

    /**
     * single category routes
     */
    Route::group(['namespace' => 'Single'], function(){
        Route::resource('singlecategory', 'SingleCategoryController');
    });
    Route::post('singlecategory/change_status/{id}','Single\SingleCategoryController@change_status');
    Route::post('singlecategory/re-order', 'Single\SingleCategoryController@reOrder')->name('singlecategory.reorder');
    /**
     * collage category routes
     */
    Route::group(['namespace' => 'Collage'], function(){
        Route::resource('collagecategory', 'CollageCategoryController');
    });
    Route::get('collagehomescreen','HomeScreen\HomeScreenController@collageHomescreen')->name('collagehomescreen');
    Route::post('collagecategory/change_status/{id}','Collage\CollageCategoryController@change_status');
    Route::get('collageelements','Collage\CollageCategoryController@collageElements')->name('collageelements');
    Route::post('collageelements/re-order', 'Collage\CollageCategoryController@reOrder')->name('collageelements.reorder');
    Route::post('collagecategory/category-re-order', 'Collage\CollageCategoryController@categoryreOrder')->name('collagecategory.categoryreorder');

    Route::get('singlehomescreen','Single\SingleCategoryController@singleHomescreen')->name('singlehomescreen');


        /**
     * relation routes
     */
    Route::group(['namespace' => 'Relation'], function(){
        Route::resource('relation', 'RelationController');
    });
    Route::get('homescreen_relation','Relation\RelationController@homescreen_relation')->name('homescreen_relation');
    Route::post('relation/change_status/{id}','Relation\RelationController@change_status');

    Route::post('relation_image/re-order', 'Relation\RelationController@reOrder')->name('relation_image.reorder');
    /**
     * relation Type routes
     */
    Route::group(['namespace' => 'Relation'], function(){
        Route::resource('relationtype', 'RelationTypeController');
    });
    Route::post('relationtype/change_status/{id}','Relation\RelationTypeController@change_status');
    Route::post('relationtype/re-order', 'Relation\RelationTypeController@reOrder')->name('relationtype.reorder');
    /**
     * home Screen routes
     */
    Route::group(['namespace' => 'HomeScreen'], function(){
        Route::resource('homescreen', 'HomeScreenController');
    });

    Route::get('homescreen_type/{type}','HomeScreen\HomeScreenController@typeindex')->name('homescreen_type');
    Route::post('homescreen/change_activestatus/{id}','HomeScreen\HomeScreenController@change_activestatus');
    Route::post('homescreen/change_status/{id}','HomeScreen\HomeScreenController@change_status');
    Route::post('homescreen/is_pro', 'HomeScreen\HomeScreenController@setIsPro')->name('homescreen.set_is_pro');
    Route::post('homescreen/re-order', 'HomeScreen\HomeScreenController@reOrder')->name('homescreen.reorder');

    /**
     * Posters routes
     */
    Route::group(['namespace' => 'Posters'], function(){
        Route::resource('poster', 'PosterController');
    });

    Route::post('poster/change_status/{id}','Posters\PosterController@change_status');
    Route::post('poster/is_pro', 'Posters\PosterController@setIsPro')->name('poster.set_is_pro');
    Route::post('poster/re-order', 'Posters\PosterController@reOrder')->name('poster.reorder');
    /**
     * Stickers routes
     */
    Route::group(['namespace' => 'Sticker'], function(){
        Route::resource('sticker', 'StickerController');
    });
    Route::post('sticker/change_status/{id}','Sticker\StickerController@change_status');
    Route::post('sticker/is_pro', 'Sticker\StickerController@setIsPro')->name('sticker.set_is_pro');
    Route::post('sticker/is_color', 'Sticker\StickerController@setIsColor')->name('sticker.set_is_color');
    Route::post('sticker/re-order', 'Sticker\StickerController@reOrder')->name('sticker.reorder');
    /**
     * Category routes
     */
    Route::group(['namespace' => 'Category'], function(){
        Route::resource('category', 'CategoryController');
    });
    Route::post('category/re-order', 'Category\CategoryController@reOrder')->name('category.reorder');
    Route::post('category/change_lock/{id}','Category\CategoryController@change_lock');

    /**
     * milestone routes
     */
    Route::get('milestone','Posters\PosterController@milestone_index')->name('milestone');

    /**
     * background category routes
     */
    Route::group(['namespace' => 'Background'], function(){
        Route::resource('backgroundcategory', 'BackgorundCategoryController');
    });
    Route::post('backgroundcategory/change_status/{id}','Background\BackgorundCategoryController@change_status');
    Route::post('backgroundcategory/re-order', 'Background\BackgorundCategoryController@reOrder')->name('backgroundcategory.reorder');

    /**
     * background routes
     */

    Route::group(['namespace' => 'Background'], function(){
        Route::resource('background', 'BackgorundController');
    });

    Route::post('background/change_status/{id}','Background\BackgorundController@change_status');
    Route::post('background/is_pro', 'Background\BackgorundController@setIsPro')->name('background.set_is_pro');
    Route::post('background/re-order', 'Background\BackgorundController@reOrder')->name('background.reorder');

    /**
     * Key routes
     */
    Route::group(['namespace' => 'Setting'], function(){
        Route::resource('setting', 'SettingController');
    });
    Route::post('setting/change_status/{id}','Setting\SettingController@change_status');

    /**
     * Font routes
     */
    Route::group(['namespace' => 'Font'], function(){
        Route::resource('font', 'FontController');
    });
    Route::post('font/change_status/{id}','Font\FontController@change_status');
    Route::post('font/re-order', 'Font\FontController@reOrder')->name('font.reorder');
    Route::post('font/is_pro', 'Font\FontController@setIsPro')->name('font.set_is_pro');
});

app/Http/Controllers/Relation/RelationTypeController.php
<?php

namespace App\Http\Controllers\Relation;

use App\Http\Controllers\Controller;
use App\Http\Requests\Relation\RelationTypeRequest;
use App\Models\RelationType;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class RelationTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->filled('api')){
            return Datatables::of(RelationType::orderBy('order_by','asc')->get())->make(true);
        }
        return view('pages.relation_type.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $relationtype = false;
        return view('pages.relation_type.create', compact('relationtype'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RelationTypeRequest $request)
    {
        try {
            $relationtype = new RelationType;
            $relationtype->relation_name = convert_char_UTF_8($request->name);
            $relationtype->order_by = RelationType::count() + 1;
            $relationtype->save();
            return redirect("relationtype");
//            return redirect()->back()->with('success', 'RelationType Added successfully...');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'RelationType not added...');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(RelationType $relationtype)
    {
        return view('pages.relation_type.create', compact('relationtype'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RelationTypeRequest $request, RelationType $relationtype)
    {
        try {
            $relationtype->relation_name = convert_char_UTF_8($request->name);

            $relationtype->save();
            return redirect("relationtype");
//            return redirect()->back()->with('success', 'RelationType Updated successfully...');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'RelationType not Updated...');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(RelationType $relationtype)
    {
        try {
            $relationtype->delete();
            return response()->json(['data' => 'RelationType deleted successfully...', 'status' => '1']);
        } catch (Exception $e) {
            return response()->json(['data' => 'Relationtype not Deleted...', 'status' => '0']);
        }
    }

    public function change_status($id)
    {
        try {
            $value = ( $_POST['data'] && $_POST['data'] == "1" ) ? 0 : 1;
            $entity = RelationType::where('id', $id)->first();
            $entity->is_active = $value;

            \DB::table('home_screens')
                ->where('relation_type_id', $id)
                ->update(['is_active' => $value]);

            if( $entity->save()){
                return response()->json(['data' => 'category Status changed...', 'status' => '1']);
            }else{
                return response()->json(['data' => 'category Status not changed...', 'status' => '0']);
            }

        } catch (Exception $e) {
            return response()->json(['data' => 'category Status not changed...', 'status' => '0']);
        }
    }

    public function reOrder(Request $request)
    {
        $request->items = array_filter($request->items);
        foreach ($request->items as $key => $val) {
            $entity = RelationType::find($val);
            $entity->order_by = $key;
            $entity->save();
        }
    }
}

resources/views/pages/relation_type/create.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container py-5" style="padding:10px;">

        <div class="row">
            <div class="col-lg-12 mb-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="h6 text-uppercase mb-0">Save RelationType</h3>
                    </div>
                    <div class="card-body">
                        @if(Session::has('success'))
                            <div class="alert alert-success">{{ Session::get('success') }}</div>
                        @endif
                        @if(Session::has('error'))
                            <div class="alert alert-danger">{{ Session::get('error') }}</div>
                        @endif
                        <form method="post" action="{{($relationtype) ? route('relationtype.update',$relationtype->id) : route('relationtype.store')}}" enctype="multipart/form-data">
                            @csrf
                            @if($relationtype)
                                @method('patch')
                            @endif
                            <div class="form-group">
                                <label class="form-control-label text-uppercase">Name</label>
                                <input type="text" placeholder="Relation name" name="name" class="form-control" value="{{(@$relationtype) ? $relationtype->relation_name :  old('name') }}">
                                @if ($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/relation_type/index.blade.php
@extends('layouts.layout')
@section('content')
    <div class="container">
        <div class="row p-xl-5">
            <div class="col-md-9">
                <h2>Relation Type</h2>
            </div>
            <div class="col-md-3">
                <a class="btn btn-lg form-control add-btn pull-right" href="{{ route('relationtype.create') }}">Create Relation Type</a>
            </div>
            <div class="col-md-12">
                <table class="table table-striped" id="relationtype-table">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Is_Active</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var crawlapps_baby_dashboard = {
            init: function () {
                this.datatableInit();
                this.relationtype_delete();
                this.change_status();
            },
            datatableInit: function(){
                var ajax_url = '';
                ajax_url = "{{ route('relationtype.index')}}?api=1";
                var i=1;
                $relationtype_table = $('#relationtype-table').DataTable({
                    "serverSide": true,
                    "destroy": true,
                    "ajax": ajax_url,
                    "columns": [
                        {"data": "id"},
                        {"data": "relation_name"},
                    ],
                    "columnDefs": [
                        {
                            "render": function (data, type, row) {
                                return i++;
                            },
                            "targets": 0,
                        },
                        {
                            "render": function (data, type, row) {
                                let r1 = "{{route('relation.index',"__")}}"
                                r1 = r1.replace("__", "id="+row.id);
                                return `<a href="`+r1+`" >`+ row.relation_name + `</a>`;
                            },
                            "targets": 1,
                        },
                        {
                            "render": function (data, type, row) {
                                var check = (row.is_active == 1) ? 'checked' : '';
                                return `<label class="label-switch switch-success">
                                    <input type="checkbox" class="switch switch-bootstrap status chng-status" name="status" id="status" value="1"` + check + ` data-value="` + row.is_active + `" data-id="`+ row.id +`">
                                    <span class="lable"></span></label>`;

                            },
                            "targets": 2,
                        },
                        {
                            "render": function (data, type, row) {
                                let r1 = "{{route('relationtype.edit',"__")}}"
                                let r3 = "{{route('relationtype.destroy',"__")}}";
                                r1 = r1.replace("__", row.id);
                                r3 = r3.replace("__", row.id);
                                return  `<a href="`+r1+`" class="btn btn-info"><i class="fa fa-pencil"></i></a>
                                    <button class="btn btn-danger del-relationtype" data-id="`+row.id+`"  type="submit"><i class="fa fa-trash-o"></i></button>`
                            },
                            "targets": 3,
                        },
                    ],
                    "pageLength": 50,
                    "lengthChange": false,
                    "orderable": false,
                    "bSort": false,
                    "bInfo": false,

                    rowReorder: true,
                    'createdRow': function (row, data, dataIndex) {
                        $(row).attr({
                            'id': data.id,
                            /*'data-webapp_code': data.webapp_id,*/
                        });
                    },
                    "fnDrawCallback": function() {
                        i=0;
                        // $('.input-checkbox').bootstrapToggle();
                    },
                });
                $relationtype_table.on( 'row-reorder', function ( e, details, edit ) {

                    var data = [];
                    for ( var i=0; i < details.length ; i++ ) {
                        data[details[i].newPosition] = details[i].node.id;
                    }
                    data = {
                        'items' : data,
                        "_token": "{{ csrf_token() }}",
                    };
                    $.ajax({
                        type: 'POST',
                        url:  "{{ route('relationtype.reorder')  }}",
                        data: data,
                        success: function (data) {
                            $relationtype_table.ajax.reload();
                        }
                    })
                });
            },
            relationtype_delete: function () {
                $(document).on('click', '.del-relationtype', function () {
                    var id = $(this).data('id');
                    swal({
                            title: "Are you sure?",
                            text: "To delete this Relation Type...",
                            icon: "warning",
                            buttons: true,
                            dangerMode: true,
                            showCancelButton: true,
                            cancelButtonText: 'Cancel',
                            closeOnConfirm: false,
                            closeOnCancel: true
                        },
                        function () {
                            let url = "{{route('relationtype.destroy',"__")}}";
                            url = url.replace("__", id);
                            $.ajax({
                                url: url,
                                type: "post",
                                data: {'_method': 'delete', '_token': "{{ csrf_token() }}"},
                                success: function (data) {
                                    swal({
                                        icon: "success",
                                    });
                                    if (data['status'] == "1") {
                                        window.location.reload();
                                    }
                                },
                            });
                        });
                });
            },

            change_status: function () {
                $(document).on('change', '.chng-status', function () {
                    var value = $(this).data('value');
                    var id = $(this).data('id');
                    let url = "{{url('relationtype/change_status',"__")}}";
                    url = url.replace("__", id);
                    $.ajax({
                        url: url,
                        type: "post",
                        data: {'_method': 'post', '_token': "{{ csrf_token() }}", 'data': value},
                        success: function (data) {
                            console.log(data);
                            // window.location.reload();
                        },
                    });
                });
            },
        };

        $(document).ready(function(){
            crawlapps_baby_dashboard.init();
        });
    </script>
@endsection